y = int(input("Ingrese un Año entre 1800 y 2001: "))
a = round(y % 19) #Hallar el residuo de y entre 19 y almacenarlo en a.
b = round(y / 100) #Hallar el cociente de y entre 100
c = round(y % 100) # Hallar el reciduo de y entre 100
d = round(b / 4)
e = round(b % 4)
g = round((8*b + 13) / 25)
h = round(19*a + b - d - g + 15 % 30)
j = round(c / 4)
k = round(c % 4)
m = round((a + (11*h)) / 319)
r = round(2*e + 2*j + (-k - h + m + 32) % 7)
n = round((h - m + r + 90) / 25)
p = round((h - m + r + n + 19) % 32)
print("Revision de resultados: ")
print(a)
print(h)
print(n)
print(b)
print(c)
print(j)
print(k)
print(p)
print(d)
print(e)
print(m)
print(g)
print(r)
print("en el", y, "la fecha de pascua fue: ")
